@startuml ERD

object Task {
  -id : ObjectID <<generated>>
  --
  ~projectId: ObjectID
  ~owner: ObjectID
  ~createdBy: ObjectID
  ~isChildOf: ObjectID
  --
  *taskName : string
  *startDate: date
  *dueDate: date
  *createdAt: date
  *updatedAt: date
  *doneAt: date
  *status: "todo | doing | done"
}

object Project {
  -id: ObjectID
  --
  ~createdBy: objectID
  --
  *projectName: string
  *description: string
  *isActive: string
  *isDeleted: boolean
  *createdAt: date
  *updatedAt: date
}

object User {
  -id : ObjectID <<generated>>
  --
  *username: string
  *fullName: string
  *password: string
  *status: string
  *role: string
  *createdAt: date
  *updatedAt: date
}
object ProjectUser {
  ~project: ObjectID
  ~user: ObjectID
}

User ||-right-o{ ProjectUser
ProjectUser }o-right-|| Project
Project||--o{ Task: has
User ||-down-o{ Task: is owner of
Task |o--o| Task: is previous task of

@enduml
