@startuml ERD

object "Task" as task {
  *id : string <<generated>>
  *taskName : string
  *createdAt: date
  *isDone: boolean
}

object "Project" as project {
  *id: string
  *projectName: string
  *createdAt: date
  *finishedAt: date
}

object "User" as user {
  *id : string <<generated>>
  *username: string
  *fullName: string
  *password: string
  *status: string
  *role: string
}

project||..o{ task
user }o..o{ project: is member of
user ||..o{ task: is owner of
task |o..o| task: is previous task of

@enduml
