@startuml ERD

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "Task" as task {
  *id : string <<generated>>
  *taskName : string
  *createdAt: date
  *isDone: boolean
  --
  *previousTask: <<FK>>
  *owner: <<FK>>
  *project: <<FK>>
}

entity "Project" as project {
  *id : string <<generated>>
  *projectId: string
  *projectName: string
  *createdAt: date
  *finishedAt: date
  --
  *members :  <<FK>>
}

entity "User" as user {
  *id : string <<generated>>
  *username: string
  *fullName: string
  *password: string
  *status: string
  *role: string
}

project||..o{ task
user }o..o{ project
task }o..|| user
task |o..o| task

@enduml
