
@startuml

left to right direction
(task management) ..> (view and edit my task): <<include>>
(task management) ..> (create task): <<include>>
(task management) ..> (edit task): <<include>>
(task management) ..> (done task): <<include>>
(task management) ..> (delete task): <<include>>

(project management) ..> (create project): <<include>>
(project management) ..> (update project information): <<include>>
(project management) ..> (add user to project): <<include>>
(project management) ..> (finish project): <<include>>

(user management) ..> (create user): <<include>>
(user management) ..> (disable user): <<include>>

(edit profile)..> (update profile information): <<include>>
(edit profile)..> (change password): <<include>>
(edit profile)..> (delete account): <<include>>

(sign in) ..> (sign in by social network): <<extend>>

(sign up) ..> (sign up by social network): <<extend>>

User --> (sign in)
User --> (sign up)
User --> (view and edit my task)
User --> (edit profile)

Admin --|> User

Admin --> (task management)
Admin -left-> (user management)
Admin --> (project management)
@enduml
